services:
    shipmonk-packing-mysql:
        image: mariadb:10.10
        ports:
            -   target: 3306
                published: 3306
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: packing
        hostname: mysql

    shipmonk-packing-app:
        depends_on:
            - shipmonk-packing-mysql
        build: .
        working_dir: /app
        user: ${UID:-1000}:${GID:-1000}
        environment:
            DB_DRIVER: ${DB_DRIVER}
            DB_HOST: ${DB_HOST}
            DB_NAME: ${DB_NAME}
            DB_USER: ${DB_USER}
            DB_PASSWORD: ${DB_PASSWORD}
            BIN_PACKING_USERNAME: ${BIN_PACKING_USERNAME}
            BIN_PACKING_API_KEY: ${BIN_PACKING_API_KEY}
            BIN_PACKING_API_URL: ${BIN_PACKING_API_URL}
        volumes:
            - .:/app

    shipmonk-packing-adminer:
        depends_on:
            - shipmonk-packing-mysql
        image: adminer:latest
        ports:
            -   target: 8080
                published: 8080
